### ISSUE TITLE
Exercise 1: User Class

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#1]
https://github.com/osifoanosike/javascript/tree/master/exercise1

Create a class User with name and age as its attribute.Instantiate two objects user1 and user2 with some valueCreate a method compare that compares the age of user1 and user2The method should be called in this way:user1.compare(user2)this method should return output like"john is older than mary" or "mary is older than john" based on their age comparision.

**Comment by abhishekjain16** [comment]
Please provide link to solution before assigning
