### ISSUE TITLE
Exercise 10. Email and URL format validation

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#10]
https://github.com/osifoanosike/javascript/tree/master/exercise10

Create two multiple selection boxFirst box contains list of countries and when you select a country and click on add button. Selected country will disappear from first box and appear in second button. And when you select a country from second box and click on remove button it will disappear from second box and appear in first box

**Comment by yuktikhurana** [comment]
1.Regex for email is not correct. Can email start with underscore, number or special chars ?
2.url can also have https or ftp. regex can be optimised
3. can this (https://github.com/osifoanosike/javascript/blob/master/exercise10/exercise10.js#L25) be included in switch too ?

**Comment by osifoanosike** [comment]
Regex corrected.
Logic updated

**Comment by yuktikhurana** [comment]
looks fine
