### ISSUE TITLE
Exercise 11. Matching numerical values and event propogation.

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#11]
https://github.com/osifoanosike/javascript/tree/master/exercise11

Exercise: Matching numerical values and event propogationCreate a form with two textfields labeled "Enter Number" and "Result". When I enter something in first textfield and submit the form, it should write true in second textfield if entered value is numeric otherwise false. Also if entered value is not numeric, form should not be submitted.Please use only Object oriented approach to write your code.

**Comment by abhishekjain16** [comment]
Please check the exercise link again

**Comment by osifoanosike** [comment]
Sorry about that. Link corrected

**Comment by abhishekjain16** [comment]
Fix Indentation first

**Comment by osifoanosike** [comment]
Done.

**Comment by abhishekjain16** [comment]
1. currform is not a good name, Please have better name.
2. event.preventDefault(); Please if this is working.

**Comment by osifoanosike** [comment]
Naming has been improved.
Yes, event.preventDefault() works, as event.defaultPrevented == true
