### ISSUE TITLE
Exercise 12.  Domain/subdomain matching

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#12]
https://github.com/osifoanosike/javascript/tree/master/exercise12

Create a simple form with a textfield and a submit button. When I enter a URL in this textfield and submit the form, it should alert me the domain name from the entered url. For example, If I enter:1. http://example.com/folder/file.html, then on submitting the form it should alert something like: Domain: example.com. 2. (with subdomain) http://vinsol.example.com/folder/file.html, then on submitting the form it should alert something like:Domain: example.com, Subdomain: vinsol.Basic Idea is to extract domain name and subdomain from a URL.Note: Use Regular Expressions for this exercise.Please use only Object oriented approach to write your code.

**Comment by mkangia** [comment]
Hey Osifo, it doesn't seem to be working as expected.
Entered www.yoman.google.com and got some funny results. Please also consider 'www' so if i enter
www.yoman.google.com it should prompt subdomain as 'yoman' and domain as 'google' 

Plus both need to come in the same prompt and not one after the other

And in case i enter www.google.com it should prompt just google as domain

Please resubmit. Also check indentation in code.

**Comment by osifoanosike** [comment]
Corrections made.

**Comment by mkangia** [comment]
Osifo,
the links given in the exercise are not working as expected.
Plus when i enter www.vinsol.osifo.google.com it returns osifo as the subdomain whereas it should be vinsol.osifo and the domain need not have '.com', it should be just google

**Comment by osifoanosike** [comment]
Errors corrected.

**Comment by mkangia** [comment]
Working well now.
Thank you.
