### ISSUE TITLE
Exercise 2. Check all or none

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#2]
https://github.com/osifoanosike/javascript/tree/master/exercise2
Create a list of checkbox (red, green, yellow, white, black). Now create two links "Check all" and 'none'. When you click on check all link all checkbox will be selected, and when you click on none link all checkbox will be deselected(working example is gmail).

**Comment by abhishekjain16** [comment]
1. Please use better var names.
2. Remove console.log from code.
3. 

```
for(var i = 0; i < that.checkboxes.length; i++) {
      if (!that.checkboxes[i].checked) {
        that.checkboxes[i].checked = true;
      }
    }
```

Can be extracted out from selectAllItems and unselectAllItems

**Comment by osifoanosike** [comment]
Hi Abhishek, please i'm not clear on the last point, the extraction. Thanks

**Comment by abhishekjain16** [comment]
By last point I meant, the code snippet above is same for both the above functions except true and false, So this can be extracted out into different method. Right?

**Comment by osifoanosike** [comment]
Okay, Corrected
