### ISSUE TITLE
Exercise 3. Maximum 3 checkbox selected

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#3]
https://github.com/osifoanosike/javascript/tree/master/exercise3

Create a list of checkboxs(Sunday, Monday, Wednesday, Thursday, Tuesday, Friday, Saturday and none). Now when I start checking these checkboxs, it should not let me check more than 3 checkboxes. When I try to check on 4th checkbox it should alert me as "Only 3 days can be selected. You have already selected sunday, monday and tuesday".Now when I click on none, all other checkboxs should be deselected. Also when 'none' is selected and I select any other option(lets assume sunday), that option(sunday) will be selected and none will be deselected.

**Comment by Shruti2791** [comment]
Make the changes as discussed.

**Comment by osifoanosike** [comment]
Changes have been implemented

**Comment by Shruti2791** [comment]
Segregate #addEventListeners into smaller methods.

**Comment by osifoanosike** [comment]
Done.

**Comment by Shruti2791** [comment]
Do as discussed.

**Comment by osifoanosike** [comment]
Corrected.

**Comment by Shruti2791** [comment]
1) Unnecessary variable assignment in line no 18, 69
2) In line no. 62 . Why do we have to pass 'that.checkboxes' . Won't that be available to this function as well ?
3) In method #uncheckAll. What if we have 10,000 checkboxes ? Iterating over each one of them and and unchecking them will become a time taking task. Think of a better method for the same.  
4) What is the purpose of the check in line no 25 ?
5) I think we have a better way to do what is being done in line no. 28.
6) We do not need to pass the value from '#limitReached' . We can simply check if selectedDays is greater than 3 or not.
7) Try optimizing method #checkItem.
8) Do not hard code the values anywhere. Take constant 3 into a variable and pass it to the class.
9) Try keeping better names for the methods and class.

**Comment by osifoanosike** [comment]
Issues corrected.
Code optimized

**Comment by Shruti2791** [comment]
1) Keep appropriate method, class and variable names. (Also mentioned in the last point above)
2) Why are we checking 'currentCheckbox.checked' condition twice ?
3) Why do we need to set classes with querySelectorAll() ?

**Comment by osifoanosike** [comment]
Fixed

**Comment by Shruti2791** [comment]
change as discussed

**Comment by osifoanosike** [comment]
Thanks, Corrected.

**Comment by Shruti2791** [comment]
Do as discussed

**Comment by osifoanosike** [comment]
Done

**Comment by Shruti2791** [comment]
looks good :+1:

**Comment by osifoanosike** [comment]
Thanks
