### ISSUE TITLE
Exercise 4.  Parent Checkbox and their children checkbox - movies, drinks and bikes

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#4]
https://github.com/osifoanosike/javascript/tree/master/exercise4

Create a div with height 100 and scroll bars. Display a list of checkbox color, drinks, movies and bikes in this div. Now when you click on color checkbox it should display four checkboxes(red, yellow, green, blue) as a child list and color checkbox should be checked with its child list of checkboxes. Again when you click on color checkbox child list should be hidden and its child checkboxes should get deselected(clear state). Same with movies, drink and bikes.movies: [Dar, Sir]drinks: [coke, pepsi, dew]bikes: [V-rod, pulsar, cbz]Remember: When you click on a parent checkbox and if child list checkboxes are out of visible area the div's scrollbars should scroll and child list should be visible automatically. We should not scroll the div to see them(child list of checkboxes).

**Comment by mkangia** [comment]
Osifo, missing functionality for clear state in case the parent checkbox is deselected. Also can we slide out the list instead of just popping them for a new UI.
Great move with the comments in the code :+1:  . Also check out the possibility of running a method just once in jQuery so we can avoid the check 
//checks so i dont have to create a new sublist everytime
      if(that.hasChild(active_list)){
        that.showChildList(active_list);
      }else {

Plus revisit code for declarations that might not be needed in case of variables. Plus get a better hold on storing the ref to the object..

**Comment by osifoanosike** [comment]
Added missing feature.
Logic updated.

**Comment by mkangia** [comment]
Osifo, i think the code got messed up. I see duplicate items getting added. Please re check and be careful with submissions.. Must check the "complete" functionality.

**Comment by osifoanosike** [comment]
Corrections made.

**Comment by mkangia** [comment]
Great Osifo.. Now this seems to be working well.
Just a couple of suggestions for further development
You can also use a hash object like
this.childList = { color: ['red', 'yellow', 'green', 'blue'], bike: ['V-rod', 'pulsar', 'cbz'] }
and then just call
this.createChildList(active_item.id, this.childList[active_item.id]);

and you could have avoided the case statements.

Moreover,
hideChildList: function (active_item){ ... }
could be
hideChildList: function (inactive_item){ ... } 

which would be more sense to hideChildList for inactive item.

Do look for more improvements. Revisit code with not the intention to finish it but improve it. :)

**Comment by osifoanosike** [comment]
Okay, Noted. Thanks
