### ISSUE TITLE
Exercise 5. Dynamic Table - add rows, edit and delete existing rows

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#5]
https://github.com/osifoanosike/javascript/tree/master/exercise5

Create a table 
When you click on 'Add new row' button:
It should add a new row in the table.
In the name and email column there will a textfield.
In the action column there will be a button save.
When you enter some value in textfields and click save, then:
Values will be saved(if valid). i.e. Name should be present, Email should be a valid email.
Textfields will be replaced by the values entered.
Save button will be replace by edit / delete links.
You should be able to delete row by clicking on the delete link, and edit value by clicking on the edit link.

**Comment by yuktikhurana** [comment]
1. for isValidInput please check for a valid email
2. Let's not depend on this.classList[1]

**Comment by osifoanosike** [comment]
Corrected.

**Comment by yuktikhurana** [comment]
looks good
