### ISSUE TITLE
Exercise 6. Form validation using js

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#6]
https://github.com/osifoanosike/javascript/tree/master/exercise6

Create a form like https://www.dropbox.com/s/qccm98brx2hdbrw/Form_validation.png and add JS validations to that form.When you click on 'Go' JS will check all text fields, and give an alert like "Login Id can't be empty". One alert per empty field.

**Comment by Shruti2791** [comment]
Can we keep better variable and method names ?
The logic for validating the length of name should be extracted in a separate method as well.

**Comment by osifoanosike** [comment]
Corrected

**Comment by Shruti2791** [comment]
1) Segregate #validateForm into smaller simpler methods.
2) Do not make 'that' globally available for the class. Rather take this's reference wherever required. Discuss if any query.
3) I think the question requires a mandatory check for the notification checkbox and not a confirmation message. Please change accordingly

**Comment by osifoanosike** [comment]
Corrections have been made

**Comment by Shruti2791** [comment]
1) We can directly check the return value of validatForm method inside if condition. (Line no 53 and 54)
2) 'notifCheckbox' being passed to the class is nowhere being used. Remove it if not required.

### Functionality issues :

1) Show errors one by one.

**Comment by osifoanosike** [comment]
Issues Fixed.

**Comment by Shruti2791** [comment]
Functionality issue yet not fixed.

**Comment by osifoanosike** [comment]
Functionality now working

**Comment by Shruti2791** [comment]
### Functionality Issues:

1) About me returning 2 errors(one for empty and another for length check) if I leave it empty. This should return empty only when left blank and should return length error if some characters and entered.
2) Indentation issues.
3) We do not have to iterate over every field and check if it erroneous or not. We can have specific methods for checking the 3 types of validations we have. (Discuss if not clear)
4) :+1 for small and self-explanatory methods.

**Comment by osifoanosike** [comment]
Issues corrected

**Comment by Shruti2791** [comment]
There is a lot of code repetition in #validateFields . This can be generic.

**Comment by osifoanosike** [comment]
Fixed

**Comment by Shruti2791** [comment]
1) I think the field input iteration should only be for #validateFieldInput. We do not need to iterate #validateAboutMe and #validateFieldLength etc. until all input fields are validated. Isn't it ?

**Comment by osifoanosike** [comment]
Code has been optimized

**Comment by Shruti2791** [comment]
Do as discussed

**Comment by osifoanosike** [comment]
Fixed
