### ISSUE TITLE
Exercise 7. Name input in Alert and Welcome in page content

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#7]
https://github.com/osifoanosike/javascript/tree/master/exercise7

Create a HTML page, when it opens in Browser, it should prompt twice. Once for first name and second for last name. When you enter first and last name, it should alert you as "Hello firstname lastname."After alert it should put that text in html page.Note: Keep in mind when you take inputs from users, always consider cases where user has entered null or blank values(few white spaces). User may pressed ESC button. In such cases you should not accept the input.

**Comment by abhishekjain16** [comment]
There is no need to pass constructor option everytime.
Use trim function at one place. It is being used too many times

**Comment by osifoanosike** [comment]
Fixed
