### ISSUE TITLE
Exercise 8. Input URL and open it.

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#8]
https://github.com/osifoanosike/javascript/tree/master/exercise8

Write a Script that prompts you for a URL. If the input is an empty url it should alert you. Otherwise it should open that URL in a new window of width 400px and height 450px, without any type of bar(status bar, scroll bars etc..).

**Comment by abhishekjain16** [comment]
1. Why have we used FrameLoader as class name here. Give better name

**Comment by osifoanosike** [comment]
Naming Corrected
